name: nogozo
description: A new Flutter application.


publish_to:



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  english_words: ^3.1.3
  substring_highlight: 0.1.0
  shared_preferences: ^0.5.6
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:

    - images/gro.webp
    - images/food.png
    - images/veg.png
    - images/sta.webp
    - images/tab.jpg
    - images/others.jpg
    - images/GRO.jpg
    - images/domino.jpg
    - images/kfc.jpg
    - images/mojo.jpg
    - images/haldirams.jpg


  fonts:
    - family: Shojumaru
      fonts:
        - asset: fonts/Shojumaru-Regular.ttf






